name: mms_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.9+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  get_it: ^7.6.8
  logger: ^2.2.0
  google_fonts: ^6.2.1
  dio: ^5.4.2+1
  hive_flutter: ^1.1.0
  global_configuration: ^2.0.0-nullsafety.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  social_share: ^2.3.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.2.5
  jwt_decoder: ^2.0.1
  status_bar_control: ^3.2.1

  ntp:

dev_dependencies:
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#B53F6C"
  image: assets/images/logo3.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/cfg/